name: Security

on:
  workflow_dispatch:
  push:

permissions:
  contents: read
  pull-requests: write

jobs:
  secret-scan:
    name: Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          fetch-depth: 0

      - name: Load versions
        run: cat .versions >> "$GITHUB_ENV"

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@e0c47f4f8be36e29cdc102c57e68cb5cbf0e8d1e # 3.0.0
        env:
          GITLEAKS_VERSION: ${{ env.GITLEAKS_VERSION }}
          GITLEAKS_ENABLE_COMMENTS: false
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: true
          GITLEAKS_ENABLE_SUMMARY: true
